# Generated by Django 5.1 on 2025-06-05 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('category', models.CharField(choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('suite', 'Suite')], default='standard', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('beds', models.PositiveIntegerField(default=1)),
                ('available', models.BooleanField(default=True)),
                ('livingroom', models.ImageField(blank=True, null=True, upload_to='rooms/livingroom/')),
                ('kitchen', models.ImageField(blank=True, null=True, upload_to='rooms/kitchen/')),
                ('bathroom', models.ImageField(blank=True, null=True, upload_to='rooms/bathroom/')),
                ('bedroom', models.ImageField(blank=True, null=True, upload_to='rooms/bedroom/')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('state', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('res_code', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('res_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('behalf_of', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.room')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
